const { DataTypes } = require("sequelize");
const { sqlServerSequelize } = require("../config/sqlserver");

const CabecalhoNFe = sqlServerSequelize.define(
  "CabecalhoNFe",
  {
    gerenciadorCABNFE: { type: DataTypes.INTEGER, allowNull: false },
    versao_infNFeCABNFE: { type: DataTypes.STRING(4), allowNull: true },
    Id_infNFeCABNFE: { type: DataTypes.STRING(47), allowNull: true },
    cUF_ideCABNFE: { type: DataTypes.DECIMAL(2, 0), allowNull: true },
    cNF_ideCABNFE: { type: DataTypes.DECIMAL(8, 0), allowNull: true },
    natOp_ideCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    indPag_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    mod_ideCABNFE: { type: DataTypes.DECIMAL(2, 0), allowNull: true },
    serie_ideCABNFE: { type: DataTypes.DECIMAL(3, 0), allowNull: true },
    nNF_ideCABNFE: { type: DataTypes.DECIMAL(9, 0), allowNull: true },
    dhEmi_ideCABNFE: { type: DataTypes.DATE, allowNull: true },
    dhSaiEnt_ideCABNFE: { type: DataTypes.DATE, allowNull: true },
    tpNF_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    idDest_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    cMunFG_ideCABNFE: { type: DataTypes.DECIMAL(7, 0), allowNull: true },
    tpImp_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    tpEmis_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    cDV_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    tpAmb_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    finNFe_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    indFinal_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    indPres_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    procEmi_ideCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    verProc_ideCABNFE: { type: DataTypes.STRING(20), allowNull: true },
    dhCont_ideCABNFE: { type: DataTypes.DATE, allowNull: true },
    xJust_ideCABNFE: { type: DataTypes.STRING(256), allowNull: true },
    CNPJ_emitCABNFE: { type: DataTypes.STRING(20), allowNull: true },
    CPF_emitCABNFE: { type: DataTypes.STRING(20), allowNull: true },
    xNome_emitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xFant_emitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xLgr_enderEmitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    nro_enderEmitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xCpl_enderEmitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xBairro_enderEmitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    cMun_enderEmitCABNFE: { type: DataTypes.DECIMAL(7, 0), allowNull: true },
    xMun_enderEmitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    UF_enderEmitCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    CEP_enderEmitCABNFE: { type: DataTypes.STRING(40), allowNull: true },
    cPais_enderEmitCABNFE: { type: DataTypes.DECIMAL(4, 0), allowNull: true },
    xPais_enderEmitCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    fone_enderEmitCABNFE: { type: DataTypes.DECIMAL(14, 0), allowNull: true },
    IE_emitCABNFE: { type: DataTypes.STRING(14), allowNull: true },
    IEST_emitCABNFE: { type: DataTypes.DECIMAL(14, 0), allowNull: true },
    IM_emitCABNFE: { type: DataTypes.STRING(15), allowNull: true },
    CNAE_emitCABNFE: { type: DataTypes.DECIMAL(7, 0), allowNull: true },
    CRT_emitCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    CNPJ_avulsaCABNFE: { type: DataTypes.STRING(14), allowNull: true },
    xOrgao_avulsaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    matr_avulsaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xAgente_avulsaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    fone_avulsaCABNFE: { type: DataTypes.DECIMAL(14, 0), allowNull: true },
    UF_avulsaCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    nDAR_avulsaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    dEmi_avulsaCABNFE: { type: DataTypes.DATEONLY, allowNull: true },
    vDAR_avulsaCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    repEmi_avulsaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    dPag_avulsaCABNFE: { type: DataTypes.DATEONLY, allowNull: true },
    CNPJ_destCABNFE: { type: DataTypes.STRING(20), allowNull: true },
    CPF_destCABNFE: { type: DataTypes.STRING(20), allowNull: true },
    idEstrangeiro_destCABNFE: { type: DataTypes.STRING(20), allowNull: true },
    xNome_destCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xLgr_enderDestCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    nro_enderDestCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xCpl_enderDestCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xBairro_enderDestCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    cMun_enderDestCABNFE: { type: DataTypes.DECIMAL(7, 0), allowNull: true },
    xMun_enderDestCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    UF_enderDestCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    CEP_enderDestCABNFE: { type: DataTypes.STRING(40), allowNull: true },
    cPais_enderDestCABNFE: { type: DataTypes.DECIMAL(4, 0), allowNull: true },
    xPais_enderDestCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    fone_enderDestCABNFE: { type: DataTypes.DECIMAL(14, 0), allowNull: true },
    indIEDest_destCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    IE_destCABNFE: { type: DataTypes.STRING(14), allowNull: true },
    ISUF_destCABNFE: { type: DataTypes.DECIMAL(9, 0), allowNull: true },
    IM_destCABNFE: { type: DataTypes.STRING(15), allowNull: true },
    email_destCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    CNPJ_retiradaCABNFE: { type: DataTypes.DECIMAL(14, 0), allowNull: true },
    CPF_retiradaCABNFE: { type: DataTypes.DECIMAL(11, 0), allowNull: true },
    xLgr_retiradaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    nro_retiradaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xCpl_retiradaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xBairro_retiradaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    cMun_retiradaCABNFE: { type: DataTypes.DECIMAL(7, 0), allowNull: true },
    xMun_retiradaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    UF_retiradaCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    CNPJ_entregaCABNFE: { type: DataTypes.DECIMAL(14, 0), allowNull: true },
    CPF_entregaCABNFE: { type: DataTypes.DECIMAL(11, 0), allowNull: true },
    xLgr_entregaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    nro_entregaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xCpl_entregaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xBairro_entregaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    cMun_entregaCABNFE: { type: DataTypes.DECIMAL(7, 0), allowNull: true },
    xMun_entregaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    UF_entregaCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    vBC_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vICMS_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vICMSDeson_ICMSTotCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vBCST_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vST_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vProd_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vFrete_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vSeg_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vDesc_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vII_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vIPI_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vPIS_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vCOFINS_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vOutro_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vNF_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vTotTrib_ICMSTotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vServ_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vBC_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vISS_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vPIS_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vCOFINS_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    dCompet_ISSQNtotCABNFE: { type: DataTypes.STRING(50), allowNull: true },
    vDeducao_ISSQNtotCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vOutro_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vDescIncond_ISSQNtotCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vDescCond_ISSQNtotCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vISSRet_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    cRegTrib_ISSQNtotCABNFE: { type: DataTypes.DECIMAL(2, 0), allowNull: true },
    vRetPIS_retTribCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vRetCOFINS_retTribCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vRetCSLL_retTribCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vBCIRRF_retTribCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vIRRF_retTribCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vBCRetPrev_retTribCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vRetPrev_retTribCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    modFrete_transpCABNFE: { type: DataTypes.DECIMAL(1, 0), allowNull: true },
    CNPJ_transportaCABNFE: { type: DataTypes.DECIMAL(14, 0), allowNull: true },
    CPF_transportaCABNFE: { type: DataTypes.DECIMAL(11, 0), allowNull: true },
    xNome_transportaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    IE_transportaCABNFE: { type: DataTypes.STRING(14), allowNull: true },
    xEnder_transportaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xMun_transportaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    UF_transportaCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    vServ_retTranspCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vBCRet_retTranspCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    pICMSRet_retTranspCABNFE: {
      type: DataTypes.DECIMAL(6, 4),
      allowNull: true,
    },
    vICMSRet_retTranspCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    CFOP_retTranspCABNFE: { type: DataTypes.DECIMAL(4, 0), allowNull: true },
    cMunFG_retTranspCABNFE: { type: DataTypes.DECIMAL(7, 0), allowNull: true },
    placa_veicTranspCABNFE: { type: DataTypes.STRING(7), allowNull: true },
    UF_veicTranspCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    RNTC_veicTranspCABNFE: { type: DataTypes.STRING(20), allowNull: true },
    nFat_fatCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    vOrig_fatCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vDesc_fatCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    vLiq_fatCABNFE: { type: DataTypes.DECIMAL(15, 2), allowNull: true },
    infAdFisco_infAdicCABNFE: { type: DataTypes.STRING(2000), allowNull: true },
    infCpl_infAdicCABNF: { type: DataTypes.TEXT, allowNull: true },
    UFSaidaPais_exportaCABNFE: { type: DataTypes.STRING(2), allowNull: true },
    xLocExporta_exportaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xLocDespacho_exportaCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xNEmp_compraCABNFE: { type: DataTypes.STRING(22), allowNull: true },
    xPed_compraCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    xCont_compraCABNFE: { type: DataTypes.STRING(60), allowNull: true },
    safra_canaCABNFE: { type: DataTypes.STRING(9), allowNull: true },
    ref_canaCABNFE: { type: DataTypes.STRING(7), allowNull: true },
    situacaoCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    manifestacaoCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    xjustmanifestacaoCABNFE: { type: DataTypes.STRING(255), allowNull: true },
    vinculoemitenteCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    vinculodestinatarioCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    diferencavaloresCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    liberadorecfisicoCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    cpgtoCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    dataprocessamentoCABNFE: { type: DataTypes.DATE, allowNull: true },
    tipooperacaoCABNFE: { type: DataTypes.INTEGER, allowNull: true },
    vICMSUFDest_ICMSTotCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vICMSUFRemet_ICMSTotCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
    vFCPUFDest_ICMSTotCABNFE: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: true,
    },
  },
  {
    tableName: "tb4402_Cabecalho_NFe",
    timestamps: false,
  }
);

module.exports = CabecalhoNFe;
